### Get all books
GET http://localhost:8080/books
Accept: application/json

### Add a new book
POST http://localhost:8080/books
Accept: application/json

{
    "title": "Dart",
    "author": "Google",
    "genre": "Software Engineer"
}

### Get book by id
GET http://localhost:8080/books/2
Accept: application/json

### Update book by id
PUT http://localhost:8080/books/2
Accept: application/json

{
    "title": "Clean Code",
    "author": "Robert C. Martin",
    "genre": "Software Development"
}

### Delete book by id
DELETE http://localhost:8080/books/4
Accept: application/json